### ISSUE TITLE
atstccfg writes corrupt `logging.yaml` when filters are used.

### ISSUE THREAD

**Issue by alficles** [apache/trafficcontrol#4845]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [x] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

`logging.yaml` is corrupt because there is no newline added when a filter parameter is applied any but the last log object.

## Expected / new behavior:

Newlines should be in the correct places so that the file parses as a YAML object.

## Minimal reproduction of the problem with instructions:

Create a profile with parameters like this for `logging.yaml`:

```
LogFormat.Format: a
LogFormat.Name: a
LogFormat1.Format: b
LogFormat1.Name: b
LogFilter.Name: f
LogFilter.Filter: "{Host}cqh CONTAIN e"
LogObject.Filename: a
LogObject.Format: a
LogObject.Filters: f
LogObject1.Filename: b
LogObject1.Format: b
```

Assign the profile to a server and ask ORT to generate config files. The incorrect YAML for `logging.yaml` will look something like this:

```
formats:
 - name: a
   format: a
 - name: b
   format: b
filters:
 - name: f
   action: accept
   condition: "{Host}cqh CONTAIN e"
logs:
 - mode: ascii
   filename: a
   format: a
   filters: [f] - mode: ascii
   filename: b
   format: b
```

But it should actually look like:

```
formats:
 - name: a
   format: a
 - name: b
   format: b
filters:
 - name: f
   action: accept
   condition: "{Host}cqh CONTAIN e"
logs:
 - mode: ascii
   filename: a
   format: a
   filters: [f]
 - mode: ascii
   filename: b
   format: b
```
