### ISSUE TITLE
TP Integration Tests GHA: SE_EVENT_BUS_HOST not set, exiting!

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#6289]
## This Bug Report affects these Traffic Control components:

- Automation 
- unknown

## Current behavior:

The `chromium` service fails to start in the Traffic Portal Integration Tests GitHub Action:
```
2021-10-14 18:41:20,050 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
SE_EVENT_BUS_HOST not set, exiting!
2021-10-14 18:41:20,381 INFO exited: selenium-node (exit status 1; not expected)
```

## Expected behavior:

The `chromium` service should start successfully.

## Steps to reproduce:

Using the environment variables set in `.github/workflows/tp.integration.tests.yml`:
```yaml
<<'DOCKER_COMPOSE' docker-compose -f- up
version: '3.8'
services:
  hub:
    image: selenium/hub
  chromium:
    image: selenium/node-chrome
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    volumes:
      - /dev/shm:/dev/shm
DOCKER_COMPOSE
```
