### ISSUE TITLE
Ansible dataset_loader - not all hosts are assigned profiles by associate_profile_to_servers filter method

### ISSUE THREAD

**Issue by davidc0le** [apache/trafficcontrol#6541]
## This Bug Report affects these Traffic Control components:
- Automation (Ansible)

## Current behavior:

After the play 'Associate eligible profiles to hosts' ( 
https://github.com/apache/trafficcontrol/blob/master/infrastructure/ansible/roles/dataset_loader/tasks/dataset_loader.yml#L638 ) runs, the profile_assignments fact does not contain all of the hosts in the inventory with valid component assignments.    The method associate_profile_to_servers() does return all hosts.

I think the lowering of the case of profile names in the jinja filter is causing the issue. https://github.com/apache/trafficcontrol/blob/master/infrastructure/ansible/roles/dataset_loader/tasks/dataset_loader.yml#L642

## Expected behavior:

All hosts in the inventory with valid ATC component assignment should be in the profile_assignments  fact after  play 'Associate eligible profiles to hosts' has run.

## Steps to reproduce:
See the profile_assignment.py in the attached zip file.
[profile_assignment_issue.zip](https://github.com/apache/trafficcontrol/files/8010183/profile_assignment_issue.zip)

**Comment by davidc0le** [comment]
On closer inspection, the default profile_prefix_ansible_component_map has regex flags to allow case insensive matching. The private profile_prefix_ansible_component_map did not have that flag:

```
dl_ds_private_profile_prefix_ansible_component_map:
  cdnportal: CDN_PORTAL
  influxrelay: INFLUX_RELAY
  influxdb_telegraf: INFLUXDB_TELEGRAF
```

With adjustments to the map, the desired functionality is achieved.

```
dl_ds_private_profile_prefix_ansible_component_map:
  cdnportal: '(?i)^CDN_PORTAL$'
  influxrelay: '(?i)^INFLUX_RELAY$'
  influxdb_telegraf: '(?i)^INFLUXDB_TELEGRAF$'
```

Closing this issue, as this is not a bug.
