### ISSUE TITLE
TS cache config creates duplicate lines in ip_allow.yaml for mid servers

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [apache/trafficcontrol#7763]
## This Bug Report affects these Traffic Control components:

- Traffic Control Cache Config (`t3c`, formerly ORT)

## What did you do?

- Run CDN in a Box
- Display `ip_allow.yaml` for mid-01 or mid-02 cache servers with `docker-compose exec mid-01 cat /opt/trafficserver/etc/trafficserver/ip_allow.yaml`

## What did you expect to happen?

Single entries for `127.0.0.1`  and `::1`

## What actually happened?

```yaml
ip_allow:
  - apply: in
    ip_addrs: ::1
    action: allow
    methods:
      - ALL
  - apply: in
    ip_addrs: 127.0.0.1
    action: allow
    methods:
      - ALL
  ...
  - apply: in
    ip_addrs: 127.0.0.1
    action: allow
    methods:
      - ALL
  ...
  - apply: in
    ip_addrs: ::1
    action: allow
    methods:
      - ALL
```
